### ISSUE TITLE
Change order of options in "main menu"

### ISSUE THREAD

**Issue by Robyer** [Matasx/xmr-stak-bootstrap#4]
It feels more natural to have "Exit" (and "Exit & terminate miners") at the bottom of list, not in the middle. So rather:

1. start/restart miners
2. change solution
3. change workload
4. exit
5. exit and terminate miners

Note: Also numbering from 1. feels better than from 0. (currently start/restart miners is 0, instead of 1).

**Comment by Matasx** [comment]
This will be included in the next release.
