### ISSUE TITLE
Wait few seconds after killing old miners and starting new

### ISSUE THREAD

**Issue by Robyer** [Matasx/xmr-stak-bootstrap#6]
Currently when I choose to restart miners, there is sent kill signal to quit them and immediately after that (after sending the signal) they are started again. Here comes problem that quitting the miners might take few seconds for me, and that bootstrap should:

a) wait predefined amount of time before starting them again (e.g. 5 or 10 seconds)
b) wait until they are really killed (if that's possible)

Otherwise there might be some problems during initialization of gpus when old instances are still running.

**Comment by Matasx** [comment]
Option a) will be implemented configurable through 'd' cmd switch and defaulting to 10 seconds.
